### ISSUE TITLE
Green Keys not saving to/loading from save file correctly on Linux/macOS

### ISSUE THREAD

**Issue by WandeingLagomorph793** [Render96/Render96ex#7]
**Describe the bug**
So it's a bit tricky to explain, but whenever I collect one of the green keys, it does not save correctly. It'll save the first key from Bobomb Battlefield, but no others. even if the first key I got wasn't from BoB.

If I edit the save file after compiling with "text saves", I can add in the amount of 1's needed to obtain all the keys, but saving a star or anything after that reverts it, where the save file only says 1, rather than how many zeroes.

Everything else saves just find, stars and caps, and the unlockable the keys unlock saves if I happen to save while that's active, but switching back requires editing the save or reobtaining the keys again.

This was tested on the previous stable 1.4.2, but within the SM64 Discord I and one other user can confirm this issue persists into the current 2.0 Alpha. We're not sure if this is a Linux only issue or what it is.

**To Reproduce**
1. Go to any level with one of the keys, Bob Omb Battlefield and the Secret Slide have two quick and easy ones.
2. Pick up the key
3. Quit the game, the keys autosave but saving with a star is optional
4. Reload the game

**Expected behavior**
You should have 2 Keys

**Actual behavior**
You only have 1 key, regardless of the amount you had prior

**Desktop (please complete the following information):**
 - Manjaro Linux 5.9.1.1
 - Version Super Mario 64 Render96ex 1.4.2

**Additional context**
My version was built with the smlinux scripts, tested various configurations, including a vanilla Render96ex with no extra patches or cheats, and this issue persists within all of them.

**Comment by GammaTendonNine** [comment]
**This has been my experience as well, with a couple of minor differences:**
0) The key(s) do in fact save to the text save file correctly, including the specific level that it came from.
1) Also, as expected, the game only saves to the save file when you save in-game, just like vanilla, _NOT_ when you collect the key itself.

As you said though, when you reload the game the number of keys is not read from the save file and you have to collect them all (again) and then unlock Luigi in a single run.  The source code reflects this as there is no function to load them from the save file.  If you unlock Luigi however, this will be saved and you will be Luigi when you reload the game, but will not be able to switch back to Mario via the boo hat, rather having to edit the save file to do so.

I always assumed this was by design to facilitate the speedrun competitions that are put on in Discord, but then it doesn't make a lot of sense that the keys are saved to the save file in the first place.  Let me confirm with @DorfDork and I can look into adding the Luigi Key Loading to the Save Load functionality.

**Comment by GammaTendonNine** [comment]
This issue has been addressed with the latest Hotfix:
https://discord.com/channels/727721825953513472/730551213376143431/779172409960955905
